# Generated by Django 5.1.4 on 2024-12-15 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_payment_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
