# Generated by Django 5.1.4 on 2024-12-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_payment_link_payment_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.PositiveIntegerField(
                help_text="Укажите сумму платежа", verbose_name="Сумма платежа"
            ),
        ),
    ]
