# Generated by Django 5.1.4 on 2024-12-10 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="cours",
            field=models.ForeignKey(
                help_text="Выберите курс",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson",
                to="courses.cours",
                verbose_name="Курс",
            ),
        ),
    ]
